---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main
  namespace: gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
spec:
  gatewayClassName: cilium
  listeners:
  - name: jfp-one-http
    hostname: "jfp.one"
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
  - name: jfp-one-https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: All
    hostname: "jfp.one"
    tls:
      mode: Terminate
      certificateRefs:
      - name: jfp-one-tls
