---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway
resources:
- cluster-issuer.yaml
- namespace.yaml
- gateway.yaml
spec:
  dependsOn:
  - name: cert-manager
    kind: HelmRelease
    namespace: cert-manager
