apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nixos
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/JenSeReal/NixOS.git
  ref:
    branch: main
  secretRef:
    name: flux-git-auth
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nixos
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: nixos
  path: ./hosts/midnight-runner/kubernetes/clusters/prod
  prune: true
  wait: true
