---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: jens@plueddemann.de
    privateKeySecretRef:
      name: letsencrypt-dev-account-key
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: main
            kind: Gateway
            namespace: networking
